apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/clemens-zauchner/gitops-test-repo
      revision: HEAD
      directories:
      - path: appset-apps/*
  template:
    metadata:
      name: base-repo
      namespace: openshift-gitops
    spec:
      destination:
        namespace: "apps-{{ path.basename }}"
        server: https://kubernetes.default.svc
      project: default
      source:
        path: "apps-{{ path }}"
        repoURL: https://github.com/clemens-zauchner/gitops-test-repo
        targetRevision: HEAD
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true